#include "lapack_test.h"

int assert_close(double actual, double expect, double eps, const char* msg) {
    if (fabs(actual - expect) > eps) {
        printf("%s Test Failed: actual: %.6f, expect: %.6f\n", msg, actual, expect);
        return 1;
    }
    return 0;
}

int assert_eq_int(int actual, int expect, const char* msg) {
    if (actual != expect) {
        printf("%s Test Failed: actual: %d, expect: %d\n", msg, actual, expect);
        return 1;
    }
    return 0;
}

int main() {
    int failed = 0;

    failed += test_lapack_make_complex_float();
    failed += test_lapack_make_complex_double();
    failed += test_lapacke_sbdsdc();
    failed += test_lapacke_dbdsdc();
    failed += test_lapacke_sbdsqr();
    failed += test_lapacke_dbdsqr();
    failed += test_lapacke_cbdsqr();
    failed += test_lapacke_zbdsqr();
    failed += test_lapacke_sbdsvdx();
    failed += test_lapacke_dbdsvdx();
    failed += test_lapacke_sdisna();
    failed += test_lapacke_ddisna();
    failed += test_lapacke_sgbbrd();
    failed += test_lapacke_dgbbrd();
    failed += test_lapacke_cgbbrd();
    failed += test_lapacke_zgbbrd();
    failed += test_lapacke_sgbcon();
    failed += test_lapacke_dgbcon();
    failed += test_lapacke_cgbcon();
    failed += test_lapacke_zgbcon();
    failed += test_lapacke_sgbequ();
    failed += test_lapacke_dgbequ();
    failed += test_lapacke_cgbequ();
    failed += test_lapacke_zgbequ();
    failed += test_lapacke_sgbequb();
    failed += test_lapacke_dgbequb();
    failed += test_lapacke_cgbequb();
    failed += test_lapacke_zgbequb();
    failed += test_lapacke_sgbrfs();
    failed += test_lapacke_dgbrfs();
    failed += test_lapacke_cgbrfs();
    failed += test_lapacke_zgbrfs();
    failed += test_lapacke_sgbsv();
    failed += test_lapacke_dgbsv();
    failed += test_lapacke_cgbsv();
    failed += test_lapacke_zgbsv();
    failed += test_lapacke_sgbsvx();
    failed += test_lapacke_dgbsvx();
    failed += test_lapacke_cgbsvx();
    failed += test_lapacke_zgbsvx();
    failed += test_lapacke_sgbtrf();
    failed += test_lapacke_dgbtrf();
    failed += test_lapacke_cgbtrf();
    failed += test_lapacke_zgbtrf();
    failed += test_lapacke_sgbtrs();
    failed += test_lapacke_dgbtrs();
    failed += test_lapacke_cgbtrs();
    failed += test_lapacke_zgbtrs();
    failed += test_lapacke_sgebak();
    failed += test_lapacke_dgebak();
    failed += test_lapacke_cgebak();
    failed += test_lapacke_zgebak();
    failed += test_lapacke_sgebal();
    failed += test_lapacke_dgebal();
    failed += test_lapacke_cgebal();
    failed += test_lapacke_zgebal();
    failed += test_lapacke_sgebrd();
    failed += test_lapacke_dgebrd();
    failed += test_lapacke_cgebrd();
    failed += test_lapacke_zgebrd();
    failed += test_lapacke_sgecon();
    failed += test_lapacke_dgecon();
    failed += test_lapacke_cgecon();
    failed += test_lapacke_zgecon();
    failed += test_lapacke_sgeequ();
    failed += test_lapacke_dgeequ();
    failed += test_lapacke_cgeequ();
    failed += test_lapacke_zgeequ();
    failed += test_lapacke_sgeequb();
    failed += test_lapacke_dgeequb();
    failed += test_lapacke_cgeequb();
    failed += test_lapacke_zgeequb();
    failed += test_lapacke_sgees();
    failed += test_lapacke_dgees();
    failed += test_lapacke_cgees();
    failed += test_lapacke_zgees();
    failed += test_lapacke_sgeesx();
    failed += test_lapacke_dgeesx();
    failed += test_lapacke_cgeesx();
    failed += test_lapacke_zgeesx();
    failed += test_lapacke_sgeev();
    failed += test_lapacke_dgeev();
    failed += test_lapacke_cgeev();
    failed += test_lapacke_zgeev();
    failed += test_lapacke_sgeevx();
    failed += test_lapacke_dgeevx();
    failed += test_lapacke_cgeevx();
    failed += test_lapacke_zgeevx();
    failed += test_lapacke_sgehrd();
    failed += test_lapacke_dgehrd();
    failed += test_lapacke_cgehrd();
    failed += test_lapacke_zgehrd();
    failed += test_lapacke_sgejsv();
    failed += test_lapacke_dgejsv();
    failed += test_lapacke_cgejsv();
    failed += test_lapacke_zgejsv();
    failed += test_lapacke_sgelq2();
    failed += test_lapacke_dgelq2();
    failed += test_lapacke_cgelq2();
    failed += test_lapacke_zgelq2();
    failed += test_lapacke_sgelqf();
    failed += test_lapacke_dgelqf();
    failed += test_lapacke_cgelqf();
    failed += test_lapacke_zgelqf();
    failed += test_lapacke_sgels();
    failed += test_lapacke_dgels();
    failed += test_lapacke_cgels();
    failed += test_lapacke_zgels();
    failed += test_lapacke_sgelsd();
    failed += test_lapacke_dgelsd();
    failed += test_lapacke_cgelsd();
    failed += test_lapacke_zgelsd();
    failed += test_lapacke_sgelss();
    failed += test_lapacke_dgelss();
    failed += test_lapacke_cgelss();
    failed += test_lapacke_zgelss();
    failed += test_lapacke_sgelsy();
    failed += test_lapacke_dgelsy();
    failed += test_lapacke_cgelsy();
    failed += test_lapacke_zgelsy();
    failed += test_lapacke_sgeqlf();
    failed += test_lapacke_dgeqlf();
    failed += test_lapacke_cgeqlf();
    failed += test_lapacke_zgeqlf();
    failed += test_lapacke_sgeqp3();
    failed += test_lapacke_dgeqp3();
    failed += test_lapacke_cgeqp3();
    failed += test_lapacke_zgeqp3();
    failed += test_lapacke_sgeqpf();
    failed += test_lapacke_dgeqpf();
    failed += test_lapacke_cgeqpf();
    failed += test_lapacke_zgeqpf();
    failed += test_lapacke_sgeqr2();
    failed += test_lapacke_dgeqr2();
    failed += test_lapacke_cgeqr2();
    failed += test_lapacke_zgeqr2();
    failed += test_lapacke_sgeqrf();
    failed += test_lapacke_cgeqrf();
    failed += test_lapacke_zgeqrf();
    failed += test_lapacke_sgeqrfp();
    failed += test_lapacke_dgeqrfp();
    failed += test_lapacke_cgeqrfp();
    failed += test_lapacke_zgeqrfp();
    failed += test_lapacke_sgerfs();
    failed += test_lapacke_dgerfs();
    failed += test_lapacke_cgerfs();
    failed += test_lapacke_zgerfs();
    failed += test_lapacke_sgerqf();
    failed += test_lapacke_dgerqf();
    failed += test_lapacke_cgerqf();
    failed += test_lapacke_zgerqf();
    failed += test_lapacke_sgesdd();
    failed += test_lapacke_dgesdd();
    failed += test_lapacke_cgesdd();
    failed += test_lapacke_zgesdd();
    failed += test_lapacke_sgesv();
    failed += test_lapacke_cgesv();
    failed += test_lapacke_zgesv();
    failed += test_lapacke_dsgesv();
    failed += test_lapacke_zcgesv();
    failed += test_lapacke_sgesvd();
    failed += test_lapacke_cgesvd();
    failed += test_lapacke_zgesvd();
    failed += test_lapacke_sgesvdx();
    failed += test_lapacke_dgesvdx();
    failed += test_lapacke_cgesvdx();
    failed += test_lapacke_zgesvdx();
    failed += test_lapacke_sgesvdq();
    failed += test_lapacke_dgesvdq();
    failed += test_lapacke_cgesvdq();
    failed += test_lapacke_zgesvdq();
    failed += test_lapacke_sgesvj();
    failed += test_lapacke_dgesvj();
    failed += test_lapacke_cgesvj();
    failed += test_lapacke_zgesvj();
    failed += test_lapacke_sgesvx();
    failed += test_lapacke_dgesvx();
    failed += test_lapacke_cgesvx();
    failed += test_lapacke_zgesvx();
    failed += test_lapacke_sgetf2();
    failed += test_lapacke_dgetf2();
    failed += test_lapacke_cgetf2();
    failed += test_lapacke_zgetf2();
    failed += test_lapacke_sgetrf();
    failed += test_lapacke_cgetrf();
    failed += test_lapacke_zgetrf();
    failed += test_lapacke_sgetrf2();
    failed += test_lapacke_dgetrf2();
    failed += test_lapacke_cgetrf2();
    failed += test_lapacke_zgetrf2();
    failed += test_lapacke_sgetri();
    failed += test_lapacke_dgetri();
    failed += test_lapacke_cgetri();
    failed += test_lapacke_zgetri();
    failed += test_lapacke_sgetrs();
    failed += test_lapacke_dgetrs();
    failed += test_lapacke_cgetrs();
    failed += test_lapacke_zgetrs();
    failed += test_lapacke_sggbak();
    failed += test_lapacke_dggbak();
    failed += test_lapacke_cggbak();
    failed += test_lapacke_zggbak();
    failed += test_lapacke_sggbal();
    failed += test_lapacke_dggbal();
    failed += test_lapacke_cggbal();
    failed += test_lapacke_zggbal();
    failed += test_lapacke_sgges();
    failed += test_lapacke_dgges();
    failed += test_lapacke_cgges();
    failed += test_lapacke_zgges();
    failed += test_lapacke_sgges3();
    failed += test_lapacke_dgges3();
    failed += test_lapacke_cgges3();
    failed += test_lapacke_zgges3();
    failed += test_lapacke_sggesx();
    failed += test_lapacke_dggesx();
    failed += test_lapacke_cggesx();
    failed += test_lapacke_zggesx();
    failed += test_lapacke_sggev();
    failed += test_lapacke_dggev();
    failed += test_lapacke_cggev();
    failed += test_lapacke_zggev();
    failed += test_lapacke_sggev3();
    failed += test_lapacke_dggev3();
    failed += test_lapacke_cggev3();
    failed += test_lapacke_zggev3();
    failed += test_lapacke_sggevx();
    failed += test_lapacke_dggevx();
    failed += test_lapacke_cggevx();
    failed += test_lapacke_zggevx();
    failed += test_lapacke_sggglm();
    failed += test_lapacke_dggglm();
    failed += test_lapacke_cggglm();
    failed += test_lapacke_zggglm();
    failed += test_lapacke_sgghrd();
    failed += test_lapacke_dgghrd();
    failed += test_lapacke_cgghrd();
    failed += test_lapacke_zgghrd();
    failed += test_lapacke_sgghd3();
    failed += test_lapacke_dgghd3();
    failed += test_lapacke_cgghd3();
    failed += test_lapacke_dgesv();
    failed += test_lapacke_dgetrf();
    failed += test_lapacke_dgeqrf();
    failed += test_lapacke_dgesvd();

    if (failed > 0) {
        printf("%d tests failed.\n", failed);
        return 1;
    }
    printf("All tests passed.\n");
    return 0;
}
